  
version: '3.8'
services:
  site1:
    container_name: mywebsitename
    image: iarc/eonlineshop:commercial
    depends_on:
      - mongo1
    environment:
      PORT: 9900
      MONGO_DB_URI: mongodb://mongo1/mywebsitename
    links:
      - mongo1
    ports:
      - 6001:9900

  ssr1:
    container_name: mywebsitename-ssr
    image: iarc/eonlineshop-ssr:latest
    depends_on:
      - mongo1
    environment:
      MONGO_DB_URI: mongodb://mongo1/mywebsitename
    links:
      - mongo1
    ports:
      - 7001:9500

  mongo1:
    image: mongo
    container_name: mongo1
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
